// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getOrCreateSessionId } from '@/lib/session';

const SUPABASE_URL = "https://sepbonodwajszmmdasyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcGJvbm9kd2Fqc3ptbWRhc3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzk1MTIsImV4cCI6MjA3MDk1NTUxMn0.6yk5L0WwGqoZYy9oX_JCvfaDbQlda24S9nQz6JNUrmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      get 'x-session-id'() {
        // Include session ID for anonymous users to access their own data
        return getOrCreateSessionId();
      }
    }
  }
});